"""create catalogue items table

Revision ID: 4dbbf88cc21a
Revises: 6209bd466de9
Create Date: 2026-09-08 10:28:58.549747

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4dbbf88cc21a"
down_revision: str | Sequence[str] | None = "6209bd466de9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "catalogue_items",
        sa.Column("client_id", sa.String(length=255), nullable=False),
        sa.Column("catalogue_item_id", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("category", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint(
            "client_id", "catalogue_item_id", name=op.f("pk_catalogue_items")
        ),
    )
    op.create_index(
        "ix_catalogue_items_client_category",
        "catalogue_items",
        ["client_id", "category"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_catalogue_items_client_category", table_name="catalogue_items")
    op.drop_table("catalogue_items")
    # ### end Alembic commands ###
