"""create erasure requests table

Revision ID: 6209bd466de9
Revises: ffe153000f5a
Create Date: 2026-08-16 12:38:29.374503

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6209bd466de9"
down_revision: str | Sequence[str] | None = "ffe153000f5a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "erasure_requests",
        sa.Column("request_id", sa.String(length=36), nullable=False),
        sa.Column("client_id", sa.String(length=255), nullable=False),
        sa.Column("user_id", sa.String(length=255), nullable=False),
        sa.Column("requested_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "completed_at IS NULL OR completed_at >= verified_at",
            name=op.f("ck_erasure_requests_completed_not_before_verified"),
        ),
        sa.CheckConstraint(
            "verified_at >= requested_at",
            name=op.f("ck_erasure_requests_verified_not_before_requested"),
        ),
        sa.PrimaryKeyConstraint("request_id", name=op.f("pk_erasure_requests")),
    )
    op.create_index(
        "ix_erasure_requests_client_requested",
        "erasure_requests",
        ["client_id", "requested_at"],
        unique=False,
    )
    op.create_index(
        "ix_erasure_requests_client_user",
        "erasure_requests",
        ["client_id", "user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_erasure_requests_client_user", table_name="erasure_requests")
    op.drop_index("ix_erasure_requests_client_requested", table_name="erasure_requests")
    op.drop_table("erasure_requests")
    # ### end Alembic commands ###
